// <auto-generated />
namespace AtesShop.Admin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class initialized_admin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialized_admin));
        
        string IMigrationMetadata.Id
        {
            get { return "202003100645501_initialized_admin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
