// <auto-generated />
namespace AtesShop.Admin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class userAddressAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userAddressAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202006010706376_userAddressAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
