// <auto-generated />
namespace AtesShop.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class orderEntitiesUpdated2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(orderEntitiesUpdated2));
        
        string IMigrationMetadata.Id
        {
            get { return "202006040954219_orderEntitiesUpdated2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
