// <auto-generated />
namespace AtesShop.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class userAddressEdited4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userAddressEdited4));
        
        string IMigrationMetadata.Id
        {
            get { return "202006010848275_userAddressEdited4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
